### PR TITLE
resolved #2

### LINKED ISSUE #2: Feature unclear
The 3rd Feature segment in the README.md file is unclear

the point is rather than having interface that seems like this:
```
> Insert first number:
> Selected Operator: 
> Second number: 
```

it would be better to accept a statement like `3 + 2` then tokenize and parse it properly to the correct operation. This way it's also  possible to have the parentheses operator

### PR DESCRIPTION
**Pull request by PaprikaX33**
Need feedback from the other before merging it

### CODE REVIEW

**Comment by roidsaja** [comment]
seems good to me ppga

**Comment by roidsaja** [comment]
@PaprikaX33  it would be simpler to just use a menu system beforehand and then add the numbers up

**Comment by PaprikaX33** [comment]
We should use the menu system for a dirty and quick implementation. But it seems bad for the long run

**Comment by roidsaja** [comment]
@PaprikaX33 For the moment, its best to use menu system. Get it dirty and quickly done.

**Comment by PaprikaX33** [comment]
That's why it's a `feature`

**Comment by PaprikaX33** [comment]
Fixed in #4

**Pull request closed without merging**
